#!/bin/bash

# if the proxy and IPA is ok then you will see the following:
# 
# <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
# <html><head>
# <title>301 Moved Permanently</title>
# </head><body>
# <h1>Moved Permanently</h1>
# <p>The document has moved <a href="https://ipa.foo.local/ipa/ui">here</a>.</p>
# </body></html>

export http_proxy=http://127.0.0.1:9090
export https_proxy=$http_proxy

curl -k https://ipa.foo.local/
